default: &default
  deliver: true
  wait_on_queue_full: true
  max_payload_size: 1000012
  max_wait_timeout: 5
  wait_timeout: 0.005
  ignore_kafka_error: <%= ENV.fetch('QUEST__KAFKA__IGNORE_KAFKA_ERRORS') { 'true' } %>
  auth:
    kind: 'sasl_plaintext'
    sasl_mechanism: <%= ENV.fetch('KAFKA_SASL_DSN'){ 'SCRAM-SHA-512:kafka_login:kafka_password' }.split(':').first %>
    sasl_username: <%= ENV.fetch('KAFKA_SASL_DSN'){ 'SCRAM-SHA-512:kafka_login:kafka_password' }.split(':').second %>
    sasl_password: <%= ENV.fetch('KAFKA_SASL_DSN'){ 'SCRAM-SHA-512:kafka_login:kafka_password' }.split(':').last %>
  kafka:
    servers: <%= ENV.fetch('BROKER_URL'){ 'localhost:9092' } %>
    max_retries: <%= ENV.fetch('QUEST__KAFKA__PRODUCER__MAX_RETRIES') { 2 }%>
    required_acks: <%= ENV.fetch('QUEST__KAFKA__PRODUCER_REQUIRED_ACKS') { -1 }%>
    ack_timeout: <%= ENV.fetch('QUEST__KAFKA__PRODUCER_ACK_TIMEOUT') { 1 }%>
    retry_backoff: <%= ENV.fetch('QUEST__KAFKA__PRODUCER_RETRY_BACKOFF') { 1 }%>
    connect_timeout: <%= ENV.fetch('QUEST__KAFKA__PRODUCER_CONNECT_TIMEOUT') { 1 }%>
development:
  <<: *default
  auth:
    kind: 'plaintext'
test:
  <<: *default
  deliver: false
  wait_on_queue_full: false
  auth:
    kind: 'plaintext'
staging: &staging
  <<: *default
production:
  <<: *staging
