# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quest/events/order.proto

require "google/protobuf"

require "google/protobuf/timestamp_pb"
require "google/type/money_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("quest/events/order.proto", syntax: :proto3) do
    add_message "protobuf.order_data.Order" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :qty, :int32, 3
      optional :status, :enum, 4, "protobuf.order_data.Order.OrderStatus"
      optional :description, :string, 5
      optional :price, :message, 6, "google.type.Money"
      optional :created_at, :message, 7, "google.protobuf.Timestamp"
      optional :updated_at, :message, 8, "google.protobuf.Timestamp"
    end
    add_enum "protobuf.order_data.Order.OrderStatus" do
      value :PENDING, 0
      value :COMPLETED, 1
      value :CANCELED, 2
    end
  end
end

module Protobuf
  module OrderData
    Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.order_data.Order").msgclass
    Order::OrderStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf.order_data.Order.OrderStatus").enummodule
  end
end
