x-environments: &environments
  HISTFILE: /app/log/.bash_history
  EDITOR: vim
  prometheus_multiproc_dir: ./tmp
  BUNDLE_APP_CONFIG: ../.bundle
  DATABASE_URL: postgres://postgres:keepinsecret@postgres:5432
  REDIS_URL: redis://redis:6379
  BROKER_URL: kafka:9092

x-ruby: &ruby
  build:
    context: .
    dockerfile: ./Dockerfile
    args:
      # Keep in sync with Gitlab CI configs
      BASE_IMAGE: ruby:3.3-bookworm
      POSTGRES_VERSION: '16'
      RUBYGEMS_VERSION: '3.5.6'
      BUNDLER_VERSION: '2.5.5'
  image: quest-dev:1.0.0
  environment:
    <<: *environments
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true
  working_dir: ${WORK_DIR:-/app}
  volumes:
    - ..:/app:cached
    - ${SBMT_RUBY_GEMS_PATH:-../..}:/gems:cached
    - .psqlrc:/root/.psqlrc:ro
    # We store Rails cache and gems in volumes to get speed up on Docker for Mac
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
  networks:
    - default
    - postgres-net
    - kafka-net
  extra_hosts:
    - "quest.lvh.me:host-gateway"

x-rails-deps: &rails-deps
  redis:
    condition: service_healthy

x-rails: &rails
  <<: *ruby
  depends_on:
    <<: *rails-deps

name: voyage

services:
  backend:
    <<: *rails
    command: /bin/bash
    profiles:
      - donotstart

  puma:
    <<: *rails
    command: bundle exec puma
    environment:
      <<: *environments
      VIRTUAL_HOST: voyage.lvh.me
    networks:
      - default
      - nginx-net
      - postgres-net
      - kafka-net
    ports:
      - 3000

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq -C config/sidekiq.yml

  schked:
    <<: *rails
    command: bundle exec schked start

  outbox:
    <<: *rails
    command: bundle exec outbox start

  consumer:
    <<: *rails
    depends_on:
      <<: *rails-deps
    command: bundle exec kafka_consumer

  redis:
    image: redis:7
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 10s

volumes:
  bundle:
  redis:
  rails_cache:

networks:
  nginx-net:
    name: ${DIP_INFRA_NETWORK_NGINX}
    external: true
  postgres-net:
    name: ${DIP_INFRA_NETWORK_POSTGRES}
    external: true
  kafka-net:
    name: ${DIP_INFRA_NETWORK_KAFKA}
    external: true
