name: Quest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby w/ same version as image
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Install dependencies
        run: |
          gem install dip -v 8.0.0.rc
          dip infra up
          dip provision
      - name: Run linter
        run: dip rubocop

  test:
    name: Rspec
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Ruby w/ same version as image
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - name: Install dependencies
        run: |
          gem install dip -v 8.0.0.rc
          dip infra up
          dip provision
      - name: Run tests
        run: dip rspec --format RspecJunitFormatter --out test-results/rspec.xml --format documentation
